source 'https://github.com/sora0077/PodSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'QiitaKitDemo' do
  pod 'QiitaKit', :path => '../'
  pod 'LayoutKit', :git => 'https://github.com/sora0077/LayoutKit.git', :tag => 'v2.0.0'
  pod 'ToysBoxKit', :git => 'https://github.com/sora0077/ToysBoxKit.git', :tag => '1.0.0'
  pod 'RxSwift', '~> 2.0.0-beta'
  pod 'RxCocoa', '~> 2.0.0-beta'
  pod 'RxBlocking', '~> 2.0.0-beta'
end

target 'QiitaKitDemoUITests' do

end
